# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0002_auto_20170315_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='requirement',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
