# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0003_auto_20170315_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='requirement',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
